[[post]]
category = "Design"
title = "Zootec Web Prototyping Design"
subtitle = "The objective was to carry out a web design prototype for a microenterprise dedicated to the sale of telephone accessories."
datetime = "2022-02-05"
image = "./config/assets/posts/zzootec-1.png"
url = "https://www.figma.com/file/JPZd2emkChkpMXaukheKwd/PROTOTIPO-EMPRESA-ZZOOTEC?type=design&node-id=0%3A1&mode=design&t=yqoaT5dSHWagy2m8-1"

[[post]]
category = "Design"
title = "Android Prototyping Design PaqtaFood"
subtitle = "The objective was to carry out an Android design prototype for an invented restaurant :)"
datetime = "2023-03-14"
image = "./config/assets/posts/sv.png"
url = "https://www.figma.com/file/v8YGLq0gTTkwZ870sgnFxI/Presentacion-N%C2%B0-2?type=design&mode=design&t=yqoaT5dSHWagy2m8-1"
