############### Section config ##################
#################################################
title = "Tech Experience"
enabled = true # false

############### Technologies ####################
#################################################
# Technology I have worked with
# name = "./.../../icon_path"
[technologies]
python = "./config/assets/icons/python.svg"
git = "./config/assets/icons/git.svg"
figma = "./config/assets/icons/figma.svg"
firebase = "./config/assets/icons/firebase.svg"
pandas = "./config/assets/icons/pandas.svg"
html = "./config/assets/icons/html.svg"
jupyter = "./config/assets/icons/jupyter.svg"
